// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yxirgqxvkdyldklmspmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl4aXJncXh2a2R5bGRrbG1zcG1nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3NTcwMTgsImV4cCI6MjA3NDMzMzAxOH0.xVaVwXbcgeEUISPDhd76l8eYmG4xmcdo2oQPplSO5w4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});